package com.nuvio.app.features.player

import kotlinx.serialization.json.JsonObject

internal expect object PlayerSettingsStorage {
    fun loadShowLoadingOverlay(): Boolean?
    fun saveShowLoadingOverlay(enabled: Boolean)
    fun loadResizeMode(): String?
    fun saveResizeMode(mode: String)
    fun loadDefaultPlaybackSpeed(): Float?
    fun saveDefaultPlaybackSpeed(speed: Float)
    fun loadMouseMoveRevealsControlsEnabled(): Boolean?
    fun saveMouseMoveRevealsControlsEnabled(enabled: Boolean)
    fun loadDesktopLegacyHudEnabled(): Boolean?
    fun saveDesktopLegacyHudEnabled(enabled: Boolean)
    fun loadDesktopMinimalHudEnabled(): Boolean?
    fun saveDesktopMinimalHudEnabled(enabled: Boolean)
    fun loadDesktopUltraHudEnabled(): Boolean?
    fun saveDesktopUltraHudEnabled(enabled: Boolean)
    fun loadDesktopOfficialHudEnabled(): Boolean?
    fun saveDesktopOfficialHudEnabled(enabled: Boolean)
    fun loadDesktopMinimalHudPillsEnabled(): Boolean?
    fun saveDesktopMinimalHudPillsEnabled(enabled: Boolean)
    fun loadDesktopSeekHandleEnabled(): Boolean?
    fun saveDesktopSeekHandleEnabled(enabled: Boolean)
    fun loadDesktopHudVignetteEnabled(): Boolean?
    fun saveDesktopHudVignetteEnabled(enabled: Boolean)
    fun loadDesktopAlwaysShowClockEnabled(): Boolean?
    fun saveDesktopAlwaysShowClockEnabled(enabled: Boolean)
    fun loadDesktopPauseOverlaySourceEnabled(): Boolean?
    fun saveDesktopPauseOverlaySourceEnabled(enabled: Boolean)
    fun loadDesktopPlaybackSpeedFineIncrementsEnabled(): Boolean?
    fun saveDesktopPlaybackSpeedFineIncrementsEnabled(enabled: Boolean)
    fun loadPlaybackSpeedToggleLow(): Float?
    fun savePlaybackSpeedToggleLow(speed: Float)
    fun loadPlaybackSpeedToggleHigh(): Float?
    fun savePlaybackSpeedToggleHigh(speed: Float)
    fun loadDesktopVerboseMpvLoggingEnabled(): Boolean?
    fun saveDesktopVerboseMpvLoggingEnabled(enabled: Boolean)
    fun loadDesktopUiScalePercent(): Int?
    fun saveDesktopUiScalePercent(percent: Int)
    fun loadDesktopControlIconScalePercent(): Int?
    fun saveDesktopControlIconScalePercent(percent: Int)
    fun loadSeekStepSeconds(): Int?
    fun saveSeekStepSeconds(seconds: Int)
    fun loadDesktopSourceNotchPosition(): String?
    fun saveDesktopSourceNotchPosition(position: String)
    fun loadDesktopSourceNotchHoverEnabled(): Boolean?
    fun saveDesktopSourceNotchHoverEnabled(enabled: Boolean)
    fun loadDesktopPlayerNotificationPosition(): String?
    fun saveDesktopPlayerNotificationPosition(position: String)
    fun loadExternalPlayerEnabled(): Boolean?
    fun saveExternalPlayerEnabled(enabled: Boolean)
    fun loadExternalPlayerForwardSubtitles(): Boolean?
    fun saveExternalPlayerForwardSubtitles(enabled: Boolean)
    fun loadExternalPlayerId(): String?
    fun saveExternalPlayerId(playerId: String?)
    fun loadPreferredAudioLanguage(): String?
    fun savePreferredAudioLanguage(language: String)
    fun loadSecondaryPreferredAudioLanguage(): String?
    fun saveSecondaryPreferredAudioLanguage(language: String?)
    fun loadPreferredSubtitleLanguage(): String?
    fun savePreferredSubtitleLanguage(language: String)
    fun loadSecondaryPreferredSubtitleLanguage(): String?
    fun saveSecondaryPreferredSubtitleLanguage(language: String?)
    fun loadDualSubtitlesEnabled(): Boolean?
    fun saveDualSubtitlesEnabled(enabled: Boolean)
    fun loadPreferredSubtitleTrackKind(): String?
    fun savePreferredSubtitleTrackKind(kind: String)
    /** Pre-1.14 switches, read only to fold into the track kind. See [PlayerSettingsRepository]. */
    fun loadLegacyPreferHearingImpairedSubtitles(): Boolean?
    fun loadLegacySubtitleUseForcedSubtitles(): Boolean?
    fun loadSubtitleTextColor(): String?
    fun saveSubtitleTextColor(colorHex: String)
    fun loadSubtitleBackgroundColor(): String?
    fun saveSubtitleBackgroundColor(colorHex: String)
    fun loadSubtitleOutlineColor(): String?
    fun saveSubtitleOutlineColor(colorHex: String)
    fun loadSubtitleOutlineEnabled(): Boolean?
    fun saveSubtitleOutlineEnabled(enabled: Boolean)
    fun loadSubtitleShadowEnabled(): Boolean?
    fun saveSubtitleShadowEnabled(enabled: Boolean)
    fun loadSubtitleShadowColor(): String?
    fun saveSubtitleShadowColor(colorHex: String)
    fun loadSubtitleShadowOffset(): Int?
    fun saveSubtitleShadowOffset(offsetTenths: Int)
    fun loadSubtitleBlur(): Int?
    fun saveSubtitleBlur(blur: Int)
    fun loadSubtitleOutlineWidth(): Int?
    fun saveSubtitleOutlineWidth(width: Int)
    fun loadSubtitleBold(): Boolean?
    fun saveSubtitleBold(enabled: Boolean)
    fun loadSubtitleItalic(): Boolean?
    fun saveSubtitleItalic(enabled: Boolean)
    fun loadSubtitleFontSizeSp(): Int?
    fun saveSubtitleFontSizeSp(fontSizeSp: Int)
    fun loadSubtitleBottomOffset(): Int?
    fun saveSubtitleBottomOffset(bottomOffset: Int)
    fun loadSubtitleFontFamily(): String?
    fun saveSubtitleFontFamily(fontFamily: String)
    fun loadSubtitleAssStyleMode(): String?
    fun saveSubtitleAssStyleMode(mode: String)
    fun loadSubtitleAssScalePercent(): Int?
    fun saveSubtitleAssScalePercent(percent: Int)
    fun loadSubtitleShowOnlyPreferredLanguages(): Boolean?
    fun saveSubtitleShowOnlyPreferredLanguages(enabled: Boolean)
    fun loadAddonSubtitleStartupMode(): String?
    fun saveAddonSubtitleStartupMode(mode: String)
    fun loadPreferAddonSubtitles(): Boolean?
    fun savePreferAddonSubtitles(enabled: Boolean)
    fun loadRejectedSubtitleKeywords(): Set<String>?
    fun saveRejectedSubtitleKeywords(keywords: Set<String>)
    fun loadRejectedAudioKeywords(): Set<String>?
    fun saveRejectedAudioKeywords(keywords: Set<String>)
    fun loadStreamReuseLastLinkEnabled(): Boolean?
    fun saveStreamReuseLastLinkEnabled(enabled: Boolean)
    fun loadStreamReuseLastLinkCacheHours(): Int?
    fun saveStreamReuseLastLinkCacheHours(hours: Int)
    fun loadStreamPrefetchScope(): String?
    fun saveStreamPrefetchScope(scope: String)
    fun loadStreamPrefetchCacheMinutes(): Int?
    fun saveStreamPrefetchCacheMinutes(minutes: Int)
    fun loadStreamPrefetchResolveLinks(): Boolean?
    fun saveStreamPrefetchResolveLinks(enabled: Boolean)
    fun loadDecoderPriority(): Int?
    fun saveDecoderPriority(priority: Int)
    fun loadNvidiaRtxSuperResolutionEnabled(): Boolean?
    fun saveNvidiaRtxSuperResolutionEnabled(enabled: Boolean)
    fun loadNvidiaRtxHdrEnabled(): Boolean?
    fun saveNvidiaRtxHdrEnabled(enabled: Boolean)
    fun loadDesktopAnimeModeAutoEnabled(): Boolean?
    fun saveDesktopAnimeModeAutoEnabled(enabled: Boolean)
    fun loadDesktopAnimeTreatAnimationAsAnime(): Boolean?
    fun saveDesktopAnimeTreatAnimationAsAnime(enabled: Boolean)
    fun loadDesktopAnimeSkipUltraHdEnabled(): Boolean?
    fun saveDesktopAnimeSkipUltraHdEnabled(enabled: Boolean)
    fun loadDesktopAnimeSvpEnabled(): Boolean?
    fun saveDesktopAnimeSvpEnabled(enabled: Boolean)
    fun loadDesktopAnimeSvpDebugOverlayEnabled(): Boolean?
    fun saveDesktopAnimeSvpDebugOverlayEnabled(enabled: Boolean)
    fun loadDesktopPlaybackInfoPanelEnabled(): Boolean?
    fun saveDesktopPlaybackInfoPanelEnabled(enabled: Boolean)
    fun loadDesktopCustomShadersEnabled(): Boolean?
    fun saveDesktopCustomShadersEnabled(enabled: Boolean)
    fun loadDesktopCustomShaderPaths(): String?
    fun saveDesktopCustomShaderPaths(paths: String)
    fun loadDesktopCustomShaderSelectedPath(): String?
    fun saveDesktopCustomShaderSelectedPath(path: String)
    fun loadDesktopAudioPassthroughEnabled(): Boolean?
    fun saveDesktopAudioPassthroughEnabled(enabled: Boolean)
    /** Legacy On/Off switch, read once to migrate into [loadDesktopSeekThumbnailMode]. */
    fun loadDesktopSeekThumbnailsEnabled(): Boolean?
    fun loadDesktopSeekThumbnailMode(): String?
    fun saveDesktopSeekThumbnailMode(mode: String)
    fun loadDesktopRateLimitRecoveryMode(): String?
    fun saveDesktopRateLimitRecoveryMode(mode: String)
    fun loadDesktopRateLimitReconnectFirstDelaySeconds(): Int?
    fun saveDesktopRateLimitReconnectFirstDelaySeconds(seconds: Int)
    fun loadDesktopRateLimitReconnectSecondDelaySeconds(): Int?
    fun saveDesktopRateLimitReconnectSecondDelaySeconds(seconds: Int)
    fun loadDesktopCustomMpvOptions(): String?
    fun saveDesktopCustomMpvOptions(options: String)
    fun loadDesktopMpvConfigMode(): String?
    fun saveDesktopMpvConfigMode(mode: String)
    fun loadDesktopMpvPropertyOverrides(): String?
    fun saveDesktopMpvPropertyOverrides(serialized: String)
    fun loadMapDV7ToHevc(): Boolean?
    fun saveMapDV7ToHevc(enabled: Boolean)
    fun loadTunnelingEnabled(): Boolean?
    fun saveTunnelingEnabled(enabled: Boolean)
    fun loadStreamAutoPlayMode(): String?
    fun saveStreamAutoPlayMode(mode: String)
    fun loadStreamAutoPlaySource(): String?
    fun saveStreamAutoPlaySource(source: String)
    fun loadStreamAutoPlaySelectedAddons(): Set<String>?
    fun saveStreamAutoPlaySelectedAddons(addons: Set<String>)
    fun loadStreamAutoPlaySelectedPlugins(): Set<String>?
    fun saveStreamAutoPlaySelectedPlugins(plugins: Set<String>)
    fun loadStreamAutoPlayRegex(): String?
    fun saveStreamAutoPlayRegex(regex: String)
    fun loadStreamAutoPlayTimeoutSeconds(): Int?
    fun saveStreamAutoPlayTimeoutSeconds(seconds: Int)
    fun loadSkipIntroEnabled(): Boolean?
    fun saveSkipIntroEnabled(enabled: Boolean)
    fun loadAnimeSkipEnabled(): Boolean?
    fun saveAnimeSkipEnabled(enabled: Boolean)
    fun loadAnimeSkipClientId(): String?
    fun saveAnimeSkipClientId(clientId: String)

    fun loadSeekrApiKey(): String?
    fun saveSeekrApiKey(apiKey: String)
    fun loadIntroDbApiKey(): String?
    fun saveIntroDbApiKey(apiKey: String)
    fun loadSkipDbApiKey(): String?
    fun saveSkipDbApiKey(apiKey: String)
    fun loadSkipAutoAcceptMode(): String?
    fun saveSkipAutoAcceptMode(mode: String)
    fun loadSkipMovieCreditsToPostCredits(): Boolean?
    fun saveSkipMovieCreditsToPostCredits(enabled: Boolean)
    fun loadStripSdhSubtitles(): Boolean?
    fun saveStripSdhSubtitles(enabled: Boolean)
    fun loadIntroSubmitEnabled(): Boolean?
    fun saveIntroSubmitEnabled(enabled: Boolean)
    fun loadStreamAutoPlayNextEpisodeEnabled(): Boolean?
    fun saveStreamAutoPlayNextEpisodeEnabled(enabled: Boolean)
    fun loadStreamAutoPlayManualNextEpisode(): Boolean?
    fun saveStreamAutoPlayManualNextEpisode(enabled: Boolean)
    fun loadStreamAutoPlayPreferBingeGroup(): Boolean?
    fun saveStreamAutoPlayPreferBingeGroup(enabled: Boolean)
    fun loadStreamAutoPlayReuseBingeGroup(): Boolean?
    fun saveStreamAutoPlayReuseBingeGroup(enabled: Boolean)
    fun loadStreamFailoverEnabled(): Boolean?
    fun saveStreamFailoverEnabled(enabled: Boolean)
    fun loadStreamFailoverTimeoutSeconds(): Int?
    fun saveStreamFailoverTimeoutSeconds(seconds: Int)
    fun loadNextEpisodeThresholdMode(): String?
    fun saveNextEpisodeThresholdMode(mode: String)
    fun loadNextEpisodeThresholdPercent(): Float?
    fun saveNextEpisodeThresholdPercent(percent: Float)
    fun loadNextEpisodeThresholdMinutesBeforeEnd(): Float?
    fun saveNextEpisodeThresholdMinutesBeforeEnd(minutes: Float)
    fun loadUseLibass(): Boolean?
    fun saveUseLibass(enabled: Boolean)
    fun loadLibassRenderType(): String?
    fun saveLibassRenderType(renderType: String)
    fun loadIosVideoOutputPreset(): String?
    fun saveIosVideoOutputPreset(preset: String)
    fun loadIosToneMappingMode(): String?
    fun saveIosToneMappingMode(mode: String)
    fun loadIosTargetPrimaries(): String?
    fun saveIosTargetPrimaries(primaries: String)
    fun loadIosTargetTransfer(): String?
    fun saveIosTargetTransfer(transfer: String)
    fun loadIosHardwareDecoderMode(): String?
    fun saveIosHardwareDecoderMode(mode: String)
    fun loadIosAudioOutputMode(): String?
    fun saveIosAudioOutputMode(mode: String)
    fun loadIosExtendedDynamicRangeEnabled(): Boolean?
    fun saveIosExtendedDynamicRangeEnabled(enabled: Boolean)
    fun loadIosTargetColorspaceHintEnabled(): Boolean?
    fun saveIosTargetColorspaceHintEnabled(enabled: Boolean)
    fun loadIosHdrComputePeakEnabled(): Boolean?
    fun saveIosHdrComputePeakEnabled(enabled: Boolean)
    fun loadIosDebandEnabled(): Boolean?
    fun saveIosDebandEnabled(enabled: Boolean)
    fun loadIosInterpolationEnabled(): Boolean?
    fun saveIosInterpolationEnabled(enabled: Boolean)
    fun loadIosBrightness(): Int?
    fun saveIosBrightness(value: Int)
    fun loadIosContrast(): Int?
    fun saveIosContrast(value: Int)
    fun loadIosSaturation(): Int?
    fun saveIosSaturation(value: Int)
    fun loadIosGamma(): Int?
    fun saveIosGamma(value: Int)
    fun loadDesktopHdrMode(): String?
    fun saveDesktopHdrMode(mode: String)
    fun loadDesktopColorProfile(): String?
    fun saveDesktopColorProfile(profile: String)
    fun loadDesktopColorContrast(): Int?
    fun saveDesktopColorContrast(value: Int)
    fun loadDesktopColorBrightness(): Int?
    fun saveDesktopColorBrightness(value: Int)
    fun loadDesktopColorSaturation(): Int?
    fun saveDesktopColorSaturation(value: Int)
    fun loadDesktopColorGamma(): Int?
    fun saveDesktopColorGamma(value: Int)
    fun loadDesktopBufferPreset(): String?
    fun saveDesktopBufferPreset(preset: String)
    fun loadDesktopRendererApi(): String?
    fun saveDesktopRendererApi(api: String)
    fun loadDesktopPerformanceLogging(): Boolean?
    fun saveDesktopPerformanceLogging(enabled: Boolean)
    fun loadDesktopLowVramMode(): String?
    fun saveDesktopLowVramMode(mode: String)
    fun loadDesktopAnimeMode(): String?
    fun saveDesktopAnimeMode(mode: String)
    fun loadHeroTvTrailerEnabled(): Boolean?
    fun saveHeroTvTrailerEnabled(enabled: Boolean)
    fun loadHeroTvTrailerDelaySeconds(): Int?
    fun saveHeroTvTrailerDelaySeconds(seconds: Int)
    fun loadHeroTvTrailerSoundEnabled(): Boolean?
    fun saveHeroTvTrailerSoundEnabled(enabled: Boolean)
    fun loadHeroTvTrailerFullscreen(): Boolean?
    fun saveHeroTvTrailerFullscreen(enabled: Boolean)
    fun loadHeroTvTrailerSearchEnabled(): Boolean?
    fun saveHeroTvTrailerSearchEnabled(enabled: Boolean)
    fun exportToSyncPayload(): JsonObject
    fun replaceFromSyncPayload(payload: JsonObject)
}
