package com.nuvio.app.features.player

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
fun PlayerScreen(
    title: String,
    sourceUrl: String,
    sourceAudioUrl: String? = null,
    sourceHeaders: Map<String, String> = emptyMap(),
    sourceResponseHeaders: Map<String, String> = emptyMap(),
    streamType: String? = null,
    sourceAffinity: PlayerSourceAffinity = PlayerSourceAffinity.fromInitialStreamType(streamType),
    providerName: String,
    streamTitle: String,
    streamFilename: String? = null,
    streamSubtitle: String?,
    sourceIdentityKey: String? = null,
    initialBingeGroup: String? = null,
    pauseDescription: String? = null,
    onBack: () -> Unit,
    onPlaybackCompleted: () -> Unit = onBack,
    onOpenInExternalPlayer: ((ExternalPlayerPlaybackRequest) -> Unit)? = null,
    modifier: Modifier = Modifier,
    logo: String? = null,
    poster: String? = null,
    background: String? = null,
    seasonNumber: Int? = null,
    episodeNumber: Int? = null,
    episodeTitle: String? = null,
    episodeThumbnail: String? = null,
    releaseYear: Int? = null,
    contentType: String? = null,
    videoId: String? = null,
    parentMetaId: String,
    parentMetaType: String,
    watchProgressSource: String? = null,
    providerAddonId: String? = null,
    torrentInfoHash: String? = null,
    torrentFileIdx: Int? = null,
    torrentFilename: String? = null,
    torrentTrackers: List<String> = emptyList(),
    initialPositionMs: Long = 0L,
    initialProgressFraction: Float? = null,
    disableProgressTracking: Boolean = false,
    autoPlayMode: PlayerAutoPlayMode = PlayerAutoPlayMode.NextEpisode,
    onPlaylistHandoff: ((com.nuvio.app.features.playlist.PlaylistHandoff) -> Unit)? = null,
    onPlaylistJump: ((entryId: String) -> Unit)? = null,
) {
    PlayerScreenContent(
        PlayerScreenArgs(
            title = title,
            sourceUrl = sourceUrl,
            sourceAudioUrl = sourceAudioUrl,
            sourceHeaders = sourceHeaders,
            sourceResponseHeaders = sourceResponseHeaders,
            streamType = streamType,
            sourceAffinity = sourceAffinity,
            providerName = providerName,
            streamTitle = streamTitle,
            streamFilename = streamFilename,
            streamSubtitle = streamSubtitle,
            sourceIdentityKey = sourceIdentityKey,
            initialBingeGroup = initialBingeGroup,
            pauseDescription = pauseDescription,
            onBack = onBack,
            onPlaybackCompleted = onPlaybackCompleted,
            onOpenInExternalPlayer = onOpenInExternalPlayer,
            modifier = modifier,
            logo = logo,
            poster = poster,
            background = background,
            seasonNumber = seasonNumber,
            episodeNumber = episodeNumber,
            episodeTitle = episodeTitle,
            episodeThumbnail = episodeThumbnail,
            releaseYear = releaseYear,
            contentType = contentType,
            videoId = videoId,
            parentMetaId = parentMetaId,
            parentMetaType = parentMetaType,
            watchProgressSource = watchProgressSource,
            providerAddonId = providerAddonId,
            torrentInfoHash = torrentInfoHash,
            torrentFileIdx = torrentFileIdx,
            torrentFilename = torrentFilename,
            torrentTrackers = torrentTrackers,
            initialPositionMs = initialPositionMs,
            initialProgressFraction = initialProgressFraction,
            disableProgressTracking = disableProgressTracking,
            autoPlayMode = autoPlayMode,
            onPlaylistHandoff = onPlaylistHandoff,
            onPlaylistJump = onPlaylistJump,
        )
    )
}
